spring.application.name=Vecinity

# Configuracion de la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/vecinitydb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC

spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
logging.level.org.springframework.security=DEBUG


# Configuracion de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# Configuraci�n del servidor
server.port=8080
server.error.include-message=always

# Configuraci�n de Jackson para fechas
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.date-format=dd/MM/yyyy HH:mm:ss
spring.jackson.time-zone=Europe/Madrid

# Configuraci�n para mensajes de error personalizados
spring.messages.basename=messages
spring.messages.encoding=UTF-8
